# SPDX-FileCopyrightText: 2026 Ortan Fields
# SPDX-License-Identifier: MIT
#Minecraft server properties
#Wed May 06 22:29:05 EST 2026
allow-flight=true
allow-nether=true
announce-player-achievements=true
difficulty=3
enable-command-block=true
enable-query=false
enable-rcon=false
force-gamemode=false
gamemode=0
generate-structures=true
generator-settings=
hardcore=false
level-name=World
level-seed=testindustri
level-type=rwg
max-build-height=256
max-players=20
max-tick-time=0
motd="       \u00A77Ortan's \u00A7fGregindustri \u00A77| \u00A7f\u00A7lTesting \u00A77(test)\u00A7r\n         \u00A77[\u00A76gregindustri.moe\u00A77] \u00A77| \u00A7cGTNH 2.8.4"
online-mode=true
op-permission-level=2
pause-when-empty-seconds=0
player-idle-timeout=0
pvp=true
resource-pack=
server-id=unnamed
server-ip=
server-name=
server-port=30000
snooper-enabled=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=1
texture-pack=
view-distance=8
white-list=true
